QUESTIONS = [
    "they have 1 million followers on Instagram",
    "they have 5 million followers on Twitter",
    "they don't open their butt cheeks in the shower to let the water run through them",
    "they have no friends",
    "they were/are in a Greek organization in college",
    "they are your coworker",
    "they eat the same meal for dinner every night",
    "they are a picky eater",
    "they don't put on lotion because you can't see ash on their skin",
    "they don't have a driver license",
    "their favorite artist is Girl in Red",
    "they run like a baby deer out of the womb",
    "their favorite artist is Drake",
    "their favorite artist is Travis Scott",
    "their favorite artist is 21 Savage",
    "their favorite artist is Renee Rap",
    "their dating app bio says 'Looking for a good flirt to roast ratio'",
    "they are under 6ft (182cm) tall",
    "they are over 7ft (213cm) tall",
    "they unironically go 'weeeeee' when riding small roller coasters",
    "they don't know the difference between their, they're, and there",
    "they don't know the difference between to, too, and two",
    "everytime they get out of a vehicle, you see their buttcrack",
    "they want to become tiktok famous (unironically)",
    "they DM their favorite celebrities on social media in hopes that they respond",
    "they say 'veggies' instead of 'vegetables",
    "they are over the age of 23 and asks you to add them on snapchat",
    "they have those glasses that turn to shades in the sun",
    "they live across the country",
    "they live in a different country",
    "they are a good communicator",
    "they have terrible communication skills",
    "they haven't read a book since 6th grade",
    "they use reddit",
    "they have a PC with LED keyboard",
    "for a few weeks they smell like onions because they're switching to natural deoderant",
    "they just told you that Blink182 is 'underground' and 'lowkey'",
    "they need you to sing a lullaby at night to sleep",
    "they get all of their music from trending tiktok songs",
    "they drive cars in silence",
    "they are chronically late (1 hour+) to every event",
    "they chew with their mouth open",
    "they throw a temper tantrum when told no",
    "they did NOT make a youtube channel and post random videos in their early teens",
    "they were born after 2002",
    "they are 'naturally flirty' with everyone",
    "their favorite movie is '365 Days'",
    "their favorite tv show is 'Friends'",
    "they're still on IOS 8 or lower",
    "they fall of Lime Scooters 3 times a week",
    "they're favorite artist is Future",
    "they're favorite artist is PlayBoi Carti",
    "they're a Gemini born in May",
    "they're a Gemini born in June",
    "they're a Sagittarius born in November",
    "they're an Aries born in March",
    "they're an Aries born in April",
    "they're a Capricorn born in December",
    "they're a Capricorn born in January"
    "they're a Leo born in July",
    "they're a Leo born in August",
    "they're a Taurus born in April",
    "they're a Taurus born in May",
    "they're a Cancer born in June",
    "they're a Cancer born in July",
    "they're a Virgo born in August",
    "they're a Virgo born in September",
    "they're a Libra born in September",
    "they're a Libra born in October",
    "they're a Sagittarius born in December",
    "they're an Aquarius born in January",
    "they're an Aquarius born in February",
    "they're a Pisces born in February",
    "they're a Pisces born in March",
    "they're from Florida",
    "they're from New York",
    "they're from Montana",
    "they're from Texas",
    "they're from Georgia",
    "they were team Edward",
    "they were team Jacob",
    "lost a fight in school",
    "they correctly time the 'don't' in the one song by Bryson Tiller",
    "they're a ginger",
    "they have no social media presence",
    "they're religiously into Crypto",
    "they play Minecraft only on peaceful mode",
    "their farts are silent but ALWAYS smell like rotting eggs",
    "they ask you out via snapchat",
    "they're an Engineer",
    "their favorite member of One Direction is/was Liam",
    "their favorite member of Big Time Rush is/was Carlos",
    "they use Discord",
    "they have a finsta",
    "they call Latinx people 'spicy white'",
    "they play sims4",
    "they have the whicked whims mod on sims4",
    "they bought a switch but haven't played any games on it in over 6 months",
    "they're the oldest child",
    "they're the youngest child",
    "they drive a Subaru",
    "they have braces with YELLOW bands",
    "they're a Twitch streamer",
    "their favorite artist is Tyga",
    "their favorite artist is Jack Harlow",
    "they talk through movies/tv shows",
    "they don't use Tiktok but send you Instagram Reels",
    "they're a Business major",
    "they're a Computer Science major",
    "they randomly begin talking in a British accent anytime you converse",
    "they have the fake verified symbol next to their twitter display name",
    "they order the filet o fish at mcdonalds",
    "they post tbh's on instagram still",
    "everytime they pack a bowl they spill weed",
    "they're still in their emo phase",
    "they play Candy Crush",
    "their favorite pizza chain is Pizza Hut",
    "their favorite pizza chain is Dominos",
    "their favorite pizza chain is Papa Johns",
    "everytime they see the word 'Charcuterie board' they say 'coochie board'",
    "their favorite alcoholic drink is Hennessy",
    "they main Phoenix in the video game Valorant",
    "they dress like a Disney Channel character in the early 2010s",
    "they send super likes on tinder on purpose",
    "their favorite show is Grey's Anatomy even after they put out 18 seasons",
    "they make references from vines that are over 10 years old",
    "their favorite Marvel superhero is Captain America",
    "their favorite Marvel movie is Morbius (2022)",
    "there's nothing on the walls in their room",
]


BASE_QUESTION_LIST = [
    "they have 1 million followers on Instagram",
    "they have 5 million followers on Twitter",
    "they don't open their butt cheeks in the shower to let the water run through them",
    "they have no friends",
    "they were/are in a Greek organization in college",
    "they are your coworker",
    "they eat the same meal for dinner every night",
    "they are a picky eater",
    "they don't put on lotion because you can't see ash on their skin",
    "they don't have a driver license",
    "their favorite artist is Girl in Red",
    "they run like a baby deer out of the womb",
    "their favorite artist is Drake",
    "their favorite artist is Travis Scott",
    "their favorite artist is 21 Savage",
    "their favorite artist is Renee Rap",
    "their dating app bio says 'Looking for a good flirt to roast ratio'",
    "they are under 6ft (182cm) tall",
    "they are over 7ft (213cm) tall",
    "they unironically go 'weeeeee' when riding small roller coasters",
    "they don't know the difference between their, they're, and there",
    "they don't know the difference between to, too, and two",
    "everytime they get out of a vehicle, you see their buttcrack",
    "they want to become tiktok famous (unironically)",
    "they DM their favorite celebrities on social media in hopes that they respond",
    "they say 'veggies' instead of 'vegetables",
    "they are over the age of 23 and asks you to add them on snapchat",
    "they have those glasses that turn to shades in the sun",
    "they live across the country",
    "they live in a different country",
    "they are a good communicator",
    "they have terrible communication skills",
    "they haven't read a book since 6th grade",
    "they use reddit",
    "they have a PC with LED keyboard",
    "for a few weeks they smell like onions because they're switching to natural deoderant",
    "they just told you that Blink182 is 'underground' and 'lowkey'",
    "they need you to sing a lullaby at night to sleep",
    "they get all of their music from trending tiktok songs",
    "they drive cars in silence",
    "they are chronically late (1 hour+) to every event",
    "they chew with their mouth open",
    "they throw a temper tantrum when told no",
    "they did NOT make a youtube channel and post random videos in their early teens",
    "they were born after 2002",
    "they are 'naturally flirty' with everyone",
    "their favorite movie is '365 Days'",
    "their favorite tv show is 'Friends'",
    "they're still on IOS 8 or lower",
    "they fall of Lime Scooters 3 times a week",
    "they're favorite artist is Future",
    "they're favorite artist is PlayBoi Carti",
    "they're a Gemini born in May",
    "they're a Gemini born in June",
    "they're a Sagittarius born in November",
    "they're an Aries born in March",
    "they're an Aries born in April",
    "they're a Capricorn born in December",
    "they're a Capricorn born in January"
    "they're a Leo born in July",
    "they're a Leo born in August",
    "they're a Taurus born in April",
    "they're a Taurus born in May",
    "they're a Cancer born in June",
    "they're a Cancer born in July",
    "they're a Virgo born in August",
    "they're a Virgo born in September",
    "they're a Libra born in September",
    "they're a Libra born in October",
    "they're a Sagittarius born in December",
    "they're an Aquarius born in January",
    "they're an Aquarius born in February",
    "they're a Pisces born in February",
    "they're a Pisces born in March",
    "they're from Florida",
    "they're from New York",
    "they're from Montana",
    "they're from Texas",
    "they're from Georgia",
    "they were team Edward",
    "they were team Jacob",
    "lost a fight in school",
    "they correctly time the 'don't' in the one song by Bryson Tiller",
    "they're a ginger",
    "they have no social media presence",
    "they're religiously into Crypto",
    "they play Minecraft only on peaceful mode",
    "their farts are silent but ALWAYS smell like rotting eggs",
    "they ask you out via snapchat",
    "they're an Engineer",
    "their favorite member of One Direction is/was Liam",
    "their favorite member of Big Time Rush is/was Carlos",
    "they use Discord",
    "they have a finsta",
    "they call Latinx people 'spicy white'",
    "they play sims4",
    "they have the whicked whims mod on sims4",
    "they bought a switch but haven't played any games on it in over 6 months",
    "they're the oldest child",
    "they're the youngest child",
    "they drive a Subaru",
    "they have braces with YELLOW bands",
    "they're a Twitch streamer",
    "their favorite artist is Tyga",
    "their favorite artist is Jack Harlow",
    "they talk through movies/tv shows",
    "they don't use Tiktok but send you Instagram Reels",
    "they're a Business major",
    "they're a Computer Science major",
    "they randomly begin talking in a British accent anytime you converse",
    "they have the fake verified symbol next to their twitter display name",
    "they order the filet o fish at mcdonalds",
    "they post tbh's on instagram still",
    "everytime they pack a bowl they spill weed",
    "they're still in their emo phase",
    "they play Candy Crush",
    "their favorite pizza chain is Pizza Hut",
    "their favorite pizza chain is Dominos",
    "their favorite pizza chain is Papa Johns",
    "everytime they see the word 'Charcuterie board' they say 'coochie board'",
    "their favorite alcoholic drink is Hennessy",
    "they main Phoenix in the video game Valorant",
    "they dress like a Disney Channel character in the early 2010s",
    "they send super likes on tinder on purpose",
    "their favorite show is Grey's Anatomy even after they put out 18 seasons",
    "they make references from vines that are over 10 years old",
    "their favorite Marvel superhero is Captain America",
    "their favorite Marvel movie is Morbius (2022)",
    "there's nothing on the walls in their room",
]